# site name
prefixName: 何もできないの
siteName:  Baokker
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://baokker.github.io
description: 回忆这理想不够理想，沿途逛世间一趟只有向上
cdn: https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog
pjax: 1
# 1开启
mathjax: 0

notice: 这里是我的blog！不定期更新：随想/读书笔记/书单/教程/.. 当然也可能不更（
lazyloadImg: https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    技术: {path: /categories/技术/, fa: fa-code }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }
    # 转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /categories/书单/, fa: fa-th-list faa-bounce }, 
    # 番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    # 图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /rss/, fa: fa-rss faa-pulse }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/Baokker/cdn_for_blog/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/441978000,  title: Bilibili, desc: My bilibili, img: /img/startdash/bilibili.jpg}
  - {url: /, title: Baokker的blog ,  desc: 技术服务, img: /img/startdash/wangshiwu.jpg}

# your site build time or founded date
siteBuildingTime: 07/16/2021

#social  url, img PC端配置
social:
  github: {url: http://github.com/Baokker, img: /img/social/github.png}
  sina: {url: https://weibo.com/u/6804155266/home, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=133853873, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/fang-bi-cheng, img: /img/social/zhihu.png}
  # email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/Baokker, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/6804155266/home, fa: fa-weibo, color: dd4b39}
  qq: {url: https://user.qzone.qq.com/1048098862, fa: fa-qq, color: 25c6fe}

donate:
#paypal is still for the author
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  # wechat: /img/custom/donate/WeChanQR.jpg
  wechat: /img/custom/donate/WeChanSQ.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg


# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 188376
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: false
v_appId: 8kxJIpLP4lL5KAApW8cG8qkA-gzGzoHsz
v_appKey: JyBmNfKUPBKm7Eead9PPFjy1

# new comment system using livere
# livere: true
# livere_uid: MTAyMC81NTcwNy8zMjE3NA==
  
 # 简易信息聚合,站点共享
rss: /atom.xml